# Homebrew Formula for hello-brew
# The filename must correspond to the class name: hello-brew.rb -> HelloBrew
class HelloBrew < Formula
  desc "A simple hello world CLI installed via Homebrew"
  homepage "https://github.com/yang-wang11/homebrew-hello/blob/main/homebrew-guide.md"

  # Source download URL — points to the tar.gz auto-generated by GitHub Releases.
  url "https://github.com/yang-wang11/homebrew-hello/archive/refs/tags/v0.1.0.tar.gz"

  # SHA256 checksum — replace with the value you obtained in Step 8.
  sha256 "f85b929330dbd740fd5b0bc27e6d9122be692b696f5934ba8e5dab7aef946cc1"

  # Open-source license.
  license "MIT"

  # Build dependency: the Rust toolchain is needed at compile time.
  # Homebrew will install Rust automatically if the user doesn't have it.
  depends_on "rust" => :build

  def install
    # Use cargo to build and install the binary.
    # std_cargo_args is a Homebrew helper that automatically sets:
    #   --root=#{prefix}  (install into the Homebrew-managed directory)
    #   --path=.          (build from the current directory)
    system "cargo", "install", *std_cargo_args
  end

  # Post-install test — runs when the user executes: brew test hello-brew
  test do
    # Verify the --version output contains the expected version number.
    assert_match "0.1.0", shell_output("#{bin}/hello-brew --version")
  end
end